import {defineArrayMember, defineType} from 'sanity'

export const pageBuilderType = defineType({
  name: 'pageBuilder',
  title: 'Page builder',
  type: 'array',
  of: [
    defineArrayMember({type: 'hero'}),
    defineArrayMember({type: 'textHero'}),
    defineArrayMember({type: 'estimationBlock'}),
    defineArrayMember({type: 'estimatorHero'}),
    defineArrayMember({type: 'imageHero'}),
    defineArrayMember({type: 'imageMarquee'}),
    defineArrayMember({type: 'threeCardBlock'}),
    defineArrayMember({type: 'twoCardBlock'}),
    defineArrayMember({type: 'iconCardsBlock'}),
    defineArrayMember({type: 'leadershipStoryBlock'}),
    defineArrayMember({type: 'checklistBlock'}),
    defineArrayMember({type: 'highlightsBlock'}),
    defineArrayMember({type: 'testimonialsBlock'}),
    defineArrayMember({type: 'faqBlock'}),
    defineArrayMember({type: 'dealerFaqFormBlock'}),
    defineArrayMember({type: 'cta'}),
    defineArrayMember({type: 'logoGridBlock'}),
    defineArrayMember({type: 'financedCarsBlock'}),
    defineArrayMember({type: 'photoLogoBlock'}),
    defineArrayMember({type: 'accountLoginBlock'}),
    defineArrayMember({type: 'applyEstimatorBlock'}),
    defineArrayMember({type: 'openRolesBlock'}),
    defineArrayMember({type: 'availabilityMapBlock'}),
  ],
})
